### ISSUE TITLE
include record information related to ```elton check``` validation test report

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/elton#11]
```elton check``` is used to run a validation/compatibility check on interaction datasets. Now, the tsv formatted reports look like:

```
local	file:///home/travis/build/globalbioticinteractions/scan/
>= 500 unique messages, turning off logging.
local	found unsupported interaction type [anacardiaceae]
local	found unsupported interaction type [associated with]
local	found unsupported interaction type [cactaceae]
local	found unsupported interaction type [cupressaceae]
local	found unsupported interaction type [euphorbiaceae]
local	found unsupported interaction type [ex]
local	found unsupported interaction type [eza/zza 1]
local	found unsupported interaction type [h]
local	found unsupported interaction type [host]
local	found unsupported interaction type [larrea]
local	found unsupported interaction type [larval foodplant]
local	found unsupported interaction type [pinaceae]
local	found unsupported interaction type [platanaceae]
local	found unsupported interaction type [reared ex caenothus herbaceous recv]
local	found unsupported interaction type [reared ex cercis canadensis lot]
local	found unsupported interaction type [reared ex]
local	invalid date string [0000-00-00]
local	invalid date string [1896-00-00]
...
```

suggested to include context (e.g. record, line numbers, archive name) to help more easily find suspicious records in datasets.

inspired by https://github.com/globalbioticinteractions/scan/issues/2 .

**Comment by jhpoelen** [comment]
@neilcobb @seltmann Please suggest your desired GloBI validation report format that would help collection managers (or other interested) to check their records and take appropriate action. Ideally a minimalist version (only necessary information) and a "deluxe" version, so I can do fast implementation first and more extensive one when needed.

You can attach examples to this issue. Thanks!

Note that the current format can be seen here: https://travis-ci.org/globalbioticinteractions/scan/jobs/587910909#L416 .

**Comment by seltmann** [comment]
I am not sure about a deluxe version. Perhaps we can start with minimalist version and then get feedback as people use the service?

source (dataset address or other), catalogNumber, name of field that contains the issue from the dataset, contents of the field, GloBI elton message

https://symbiota.ccber.ucsb.edu:443/content/dwca/UCSB-IZC_DwC-A.zip,UCSB-IZC00035235,eventDate,1988-05-00,invalid date string [1988-05-00]
--

**Comment by neilcobb** [comment]
The only method that works in SCAN is the email notification that occurs at the bottom of each record detail page.  There is no flag but people regularly email curators/collection managers if they have a problem.  The email exchange below started with me emailing SI about a possible misspelling and they emailed me this morning  saying they corrected the error. The nice thing about this is that it does not matter if you are a live or snapshot collection.  Next time we harvest from SI we will get the correction. Tim Robertson is going to propose API solutions for alerting collections about individual flagged records that GBIF identifies.


[cid:image001.png@01D5720F.6E2BFC70]



Specimen being referenced: http://scan-bugs.org/portal/collections/individual/index.php?occid=24170111<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fscan-bugs.org%2Fportal%2Fcollections%2Findividual%2Findex.php%3Foccid%3D24170111&data=02%7C01%7Correllt%40si.edu%7Cf2e5e8032c114dc96e9e08d740219818%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637048385350680478&sdata=7T0ZtO9y3hESkidIQmLtJCXn3UVDVN0%2BeN48LQe0iLo%3D&reserved=0>

Hi Neil,

Just wanted to say thanks for sending us the note on the misspelling for the above specimen.  It’s now fixed on our end.

Jessica


Jessica Bird

Acting Collections Information Manager
Department of Entomology
National Museum of Natural History
Smithsonian Institution
Washington, DC 20560  USA
Phone: 502-599-3157
E-mail: birdj@si.edu<mailto:birdj@si.edu>




I assume this is a misspelling





Specimen being referenced: http://scan-bugs.org/portal/collections/individual/index.php?occid=24170111

**Comment by neilcobb** [comment]
I forgot to add to my previous email that if this minimalist notification could be appended to “record detail”  then people would see it.  If it was a separate process then maybe less likely to have people notice?   I do not know for sure

**Comment by seltmann** [comment]
I can imagine a robust version that also includes in the output how things are mapped in GloBI

source (dataset address or other), catalogNumber, name of field that contains the issue from the dataset, contents of the field, GloBI elton message,GloBI mapping
https://symbiota.ccber.ucsb.edu:443/content/dwca/UCSB-IZC_DwC-A.zip,UCSB-IZC00035235,eventDate,1988-05-00,invalid date string [1988-05-00],1988-05

**Comment by jhpoelen** [comment]
Thanks for sharing examples + ideas for minimal validation report.

Re: " Tim Robertson is going to propose API solutions for alerting collections about individual flagged records that GBIF identifies. " @neilcobb @timrobertson100 is there any existing issue / design / library I can use for inspiration?

**Comment by neilcobb** [comment]
I am just copying Tim and he can maybe jump in and let you know, this is a quote from his last email “I’ll summarise some ideas for using existing GBIF APIs in flagging records, autocomplete of scientific names etc”.

Tim, Jorrit is setting up linkages with SCAN and GloBi in preparation for a new big digitization project that will provide information on biotic associations between arthropod parasites and their vertebrate hosts. In the process he identified records with invalid dates and that led to a conversation about offering a system that would notify data providers about individual flagged records.

We already provide links to collection pages on GBIF and iDigBio that provide summary stats for corrections made and problem records.  Only a few collections use these to correct or annotate their records.

**Comment by timrobertson100** [comment]
This is just a quick reply (sorry, super busy today) but for ideas:

1. We could explore the [GBIF data validator](https://www.gbif.org/tools/data-validator) (see [sample report](https://www.gbif.org/tools/data-validator/1568816668930)). It is exposed as an API and - _in the spirit of full transparency_ - needs some attention so we could refine it with you.
2. You could use the GBIF backbone taxonomy match as a *hint* of where names may be problematic. An [example call](http://api.gbif.org/v1/species/match?name=Leptospira%20borgpetersenii) shows how e.g. authorship can be *suggested*. Users should be made clear that these are suggestions.
3. If you have live data entry then [auto-complete on scientific names](http://api.gbif.org/v1/species/suggest?q=Gadu) might be worthwhile hints
4. Checking (or suggesting) countries against coordinates such as [this example](http://api.gbif.org/v1/geocode/reverse?lat=12.23&lng=45.3) might be worthwhile

I hope this helps a little, and please bear in mind that we need to acknowledge there can be errors in the services too - although we always strive to improve - so suggest they be packaged along the lines of suggestions/hints appropriately.

**Comment by jhpoelen** [comment]
hey @timrobertson100 -

Thanks for your pointers on validation tools. 

Here's some of my thoughts:

1. **validation report** The existing ```elton check``` provides a minimalist text-based report similar to what you shared in GBIF Validation Report in https://www.gbif.org/tools/data-validator/1568816668930 . I much like how you represent the context (line number / darwin core "table") and am hoping to extend this to make a trusted link to the source data along with the annotations to highlight the investigated terms (see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/436 ) in the source data.

2. **name linking** GloBI uses [```nomer```](https://github.com/globalbioticinteractions/nomer) to produce likely linkages of provided taxon names to many other name sources, including the GBIF backbone. In consistencies in names can be uncovered by analyzing conflicts of within or across taxonomic naming schemes. ```Nomer``` can be combined with ```elton names``` and unix pipes to do things like: ```elton names | nomer append | grep NONE``` to uncover funny or similar (e.g., replace NONE -> SIMILAR_TO) names.

3. **auto-complete** Much agreed that auto-complete for terms can be quite useful! I don't have much experiences with it beyond the rudimentary fuzzy index provided by https://api.globalbioticinteractions.org/findCloseMatchesForTaxon/Homo%20SALIents . I imagine that Symbiota and other collection management tools provide naming completion for taxonomic names (please confirm @neilcobb @seltmann )

4. ** country validation ** Matching country to lat/lng makes a lot of sense, especially when dealing with clean country names. Thanks for sharing the example of your country-lat/lng validation service.   

As I am mulling over how to capture more information to enrich the elton validation reports, I'll be looking for a data validation file format. I imagine that such a data format is the basis for fancy web UIs or more mundane text-based reports. 

@timrobertson100 are you using the specific file format to capture validation results for specific data files?

**Comment by neilcobb** [comment]
Symbiota does provide autocomplete, the problem is that our taxonomic tables are incomplete.  I have never heard of nomer, it would be great if we could use it as a taxonomic reference service.  Have you corresponded with Matt Yoder or anyone from SpeciesFile/TaxonWorks?

**Comment by jhpoelen** [comment]
nomer is an off-line capable command-line tool and integrates, among other things, many existing taxonomic name services, including https://resolver.globalnames.org , ITIS web services etc. So, if you are looking for a web api to do name lookups, perhaps you might want to consider using https://resolver.globalnames.org . 

Incidentally, Global Names is being developed out of Matt Yoder @mjy group . I've worked with his group for many years and recently attended a global names workshop in Urbana, Illinois.

**Comment by neilcobb** [comment]
Thanks

**Comment by timrobertson100** [comment]
> @timrobertson100 are you using the specific file format to capture validation results for specific data files?

Nothing fancy - I don't recall the details but probably it's just a JSON file. We plan to revisit the validator and will offer a small search portal built on a transient Elasticsearch index (e.g. 48hours then deleted) and also a report that can be downloaded. We could define that report format together if you like? CC @fmendezh

**Comment by jhpoelen** [comment]
@timrobertson100 Great! Exchanging notes on a report format sounds excellent. 

As you probably saw, my current form is quite minimalist - a tsv with a dataset identifier, or namespace, and a message: 

 namespace | message
 --- | ---
 local | found unsupported interaction type [anacardiaceae]
 local | found unsupported interaction type [associated with]
 local | found unsupported interaction type [cactaceae]
 ... | ...

The "local" namespace means that the validation happened on a local dataset.

I am working to add more informative provenance so that validations can be traced back to their originating data context (e.g., archive -> file -> line number -> position as well as originating institution, collection, occurrence id etc.). These physical and logical data coordinates help to connect a specific suspicious (verbatim) data (e.g., 20120112 on line 12 in occurrence.tsv from dwca.zip) with a validation rule (e.g., not a iso8601 date) and, optionally, suggest a replacement value (e.g., 2012-01-12).

I'd be interested to see your existing work. Before I start digging into GBIF github repos, can you point me to an example json that you are currently using in the gbif validation tool?

**Comment by jhpoelen** [comment]
A basic review report can now be generated by Elton using ```elton check``` . For example, see sample below and full report attached. Closing this issue. Please report suggested improvements in new issues.

[scan-review-2019-12-27.tsv.gz](https://github.com/globalbioticinteractions/elton/files/4010452/scan-review-2019-12-27.tsv.gz)

fyi @seltmann @neilcobb 



reviewId | reviewDate | reviewer | namespace | reviewComment | archiveURI | referenceUrl | institutionCode | collectionCode | collectionId | catalogNumber | occurrenceId | sourceCitation | dataContext
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:24Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=29698880 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00042704 | 59d9da3d-e034-4a64-923b-ced6d440f637 | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:24Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=29699110 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00044318 | a10f1e7e-1b4d-40bf-9e4c-a55fcd121ff8 | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:25Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=35374416 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00055252 | 0275e0d8-998f-48ee-9b3b-a3e663a759a2 | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:25Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=35408524 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00039224 | 075c7693-0e90-4fcb-af2a-ffadeddb188c | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:25Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=35408536 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00051782 | 2661c811-c111-4e64-9ead-8a0afd05ac09 | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:27Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=22813559 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00033300 | a8c61ad5-4cda-47df-9cb6-6c64b0e71bfa | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:28Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=35408537 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00051975 | c561daf7-cada-4d06-8693-c2af477bba55 | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:28Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=35408525 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00039225 | d55e6347-d108-45f6-bbaf-613030e78d4a | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
5d03fb90-de4e-4aea-939d-882ae2314b11 | 2019-12-27T22:11:28Z | GloBI automated reviewer (elton-0.6.1) | local | no source taxon defined | https://scan-bugs.org:443/portal/content/dwca/ABS-ARTHARCH_DwC-A.zip | https://scan-bugs.org:443/portal/collections/individual/index.php?occid=35374481 | ABS | ARTHARCH | f52df103-0126-47fd-8836-934641444fcd | ARTHARCH00056756 | e7c2a4af-ca8f-41da-9839-ecd91ad68422 | Darwin Core Archive for Archbold Biological Station Arthropod Collection | omitted for brevity
