### ISSUE TITLE
suggest using review_summary for review on https://www.globalbioticinteractions.org/parasitetracker/

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/elton#36]
@jhpoelen Presently the review is not as comprehensive as the updated review_summary. Suggest to replace with review_summary, if possible.

**Comment by seltmann** [comment]
I wanted to follow up with this because I am seeing that some reviews are being built under different versions of elton. Also, the reviews linked through https://www.globalbioticinteractions.org/parasitetracker/ vary. See UCSB-IZC, vs INHS

**Comment by jhpoelen** [comment]
@seltmann great to see that you are noticing the different versions of elton. This is because the reviews are generated by independent travis build processes. Travis build processes can be configured to run periodically and this has been enabled by most (I might have missed a few).  The reason for using travis is to reduce the administrative burden to run these reviews elsewhere.  You can re-run travis processes manually if needed. Suggest to open another issue if you have ideas on how / who to manage the generation of these review reports.

**Comment by seltmann** [comment]
@jhpoelen can do! I need to understand what is happening first. I triggered a build on inhs-insects by making a commit and re-running through https://github.com/globalbioticinteractions/inhs-insects. The resulting https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/inhs-insects/indexed-interactions.tsv.gz link downloads a file that indicates that it is running elton 0.9.1. Yet, the review is done on elton 0.9.6

<img width="1054" alt="Screen Shot 2020-05-01 at 7 57 58 AM" src="https://user-images.githubusercontent.com/1044474/80814947-a2682e00-8b81-11ea-960a-f3c7311baad8.png">

**Comment by jhpoelen** [comment]
interesting! I was able to download https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/inhs-insects/review.tsv.gz and found:


reviewId | reviewDate | reviewer | namespace
-- | -- | -- | --
5a8c6c6a-3501-4e1f-a032-91453f5d8dcb | 2020-05-01T14:50:04Z | GloBI automated reviewer (elton-0.9.6) | local
5a8c6c6a-3501-4e1f-a032-91453f5d8dcb | 2020-05-01T14:50:08Z | GloBI automated reviewer (elton-0.9.6) | local
5a8c6c6a-3501-4e1f-a032-91453f5d8dcb | 2020-05-01T14:50:09Z | GloBI automated reviewer (elton-0.9.6) | local

also, from recently downloaded https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/inhs-insects/indexed-interactions.tsv.gz  - 

citation | archiveURI | lastSeenAt | contentHash | eltonVersion
-- | -- | -- | -- | --
Illinois Natural History Survey Insect Collection | file:///home/travis/build/globalbioticinteractions/inhs-insects/./ |   |   | 0.9.6
Illinois Natural History Survey Insect Collection | file:///home/travis/build/globalbioticinteractions/inhs-insects/./ |   |   | 0.9.6

So, for some reason, I don't see the version 0.9.1 you are seeing.

**Comment by jhpoelen** [comment]
btw - on a separate note, what interaction type do you think INHS's [associated with] should be mapped to?

**Comment by seltmann** [comment]
Looks like it was an unfortunate issue with browser caching.

I added a mapping to coOccursWith in the interaction_types_mapping.csv

**Comment by seltmann** [comment]
Closing and revisiting the format of the review from parasite tracker in a new issue
