### ISSUE TITLE
parasite tracker webpage index and review limit by collection

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/elton#37]
@jhpoelen the review "buttons" on the parasite tracker page link to the reviews of the datasets that those collections are contained, but are not of the individual collection. Possible to limit to the specific collection.

BYU is on scan (globalbioticinteractions/scan) can the index and review buttons only show those records with institutionCode=BYU and collectionCode=BYUC. I can fill out the collection codes in the parasitetracker.tsv for reference.

--

**Comment by jhpoelen** [comment]
@seltmann simpliest solution I can thing of with existing tools is to create a new Github repo for BYU only, similar to your UCSB-IZC https://github.com/globalbioticinteractions/ucsb-izc . Then, you can use the repository name to point directly to the report for BYU collection.

**Comment by seltmann** [comment]
I see, this makes sense. We could do this for all of the TPT partners. This makes sense. Give me the green light and I will create the repos and update the parasitetracker.tsv

**Comment by jhpoelen** [comment]
The light is green! Let me know which ones you've created, so I can enable the automated review publications from travis to GloBI. Happy to show you how this works if you'd like.

**Comment by jhpoelen** [comment]
@seltmann thanks for creating individual configurations for the specific TPT partners. Closing issue.
