### ISSUE TITLE
unexpected results from recent big-bee review

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/elton#53]
Hi @jhpoelen I was doing the quarterly review of Big Bee contributors and I am getting some unexpected results where UCSB is not showing any bee interactions and only a few other interactions. 

elton --version 0.12.5

datasets under review: 
```
EMTuckerLabUMMZ/ummzi
globalbioticinteractions/asu-asuhic
globalbioticinteractions/cas-ent
globalbioticinteractions/emec
globalbioticinteractions/fsca
globalbioticinteractions/ku-semc
globalbioticinteractions/lacm-lacmec
globalbioticinteractions/mcz
globalbioticinteractions/sdnhm-sdmc
globalbioticinteractions/ucm-ucmc
globalbioticinteractions/ucsb-izc
globalbioticinteractions/unhc-unhc
```
review summary file is truncated and review_summary_by_collection does not have as many interactions as seen at https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/ucsb-izc/README.txt

[review_summary_by_collection.txt](https://github.com/globalbioticinteractions/elton/files/9914249/review_summary_by_collection.txt)
[review_summary.txt](https://github.com/globalbioticinteractions/elton/files/9914250/review_summary.txt)

Thanks!

**Comment by jhpoelen** [comment]
@seltmann thanks for sharing your detailed notes. I am assuming you are using https://github.com/Big-Bee-Network/bigbee-globi-reporting and hoping to have a look and reproduce your results.

**Comment by jhpoelen** [comment]
I generated a big bee data report locally, and found, related to UCSB, the following items:

```
cat review_summary_by_collection.tsv | grep UCSB | mlr --itsvlite --omd cat
```

| institutionCode | collectionId | collectionCode | sourceCitation | distinctReviewCommentCount | type | comment |
| --- | --- | --- | --- | --- | --- | --- |
|  | _2 | _3 | _4 | 1 | info | [https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip]: indexing interaction records |
|  |  |  |  | 1 | info | [https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip]: scanned [34417] record(s) |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 102 | issue | found unsupported interaction type with name: [Found on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 11 | issue | source taxon name missing: using institutionCode/collectionCode/collectionId/catalogNumber/occurrenceId as placeholder |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 120 | issue | found unsupported interaction type with name: [visiting] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1364 | issue | missing interaction type |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 14 | info | biotic interaction found |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 161 | issue | found unsupported interaction type with name: [on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 16 | issue | found unsupported interaction type with name: [ex] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [Collected from] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [Collected on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [Ex] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [feeding on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [inside] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [Interspersed] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [Next to] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [reared from] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [Tended by] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 1 | issue | found unsupported interaction type with name: [Visitng] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 2 | issue | found unsupported interaction type with name: [Feeding on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 2 | issue | found unsupported interaction type with name: [In] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 2 | issue | found unsupported interaction type with name: [resting on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 3 | issue | found unsupported interaction type with name: [11] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 3 | issue | found unsupported interaction type with name: [Hovering over] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 3 | issue | found unsupported interaction type with name: [interactsWith] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 3 | issue | found unsupported interaction type with name: [Sitting on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 43 | issue | found unsupported interaction type with name: [visitsFlowersOf] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 4 | issue | found unsupported interaction type with name: [found on] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 4 | issue | found unsupported interaction type with name: [host of] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 6 | issue | found unsupported interaction type with name: [from] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 6 | issue | found unsupported interaction type with name: [under] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 77 | issue | found unsupported interaction type with name: [On] |
| UCSB | b03a3f0c-bfa5-4e02-b5d3-56ff38626302 | IZC | University of California Santa Barbara Invertebrate Zoology Collection. Accessed at <https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip> on 03 Nov 2022. | 7 | issue | found unsupported interaction type with name: [Visiting] |

**Comment by jhpoelen** [comment]
It appears that the current configuration for UCSB-IZC yield 14 interactions, instead of the almost 1800 interactions found in August 2022. Also, copy of UCSB-IZC tracked by GloBI server on 2022-11-01 yields the same results at seen on my local system today.

```
   _____ _       ____ _____   _____            _                
  / ____| |     |  _ \_   _| |  __ \          (_)               
 | |  __| | ___ | |_) || |   | |__) |_____   ___  _____      __ 
 | | |_ | |/ _ \|  _ < | |   |  _  // _ \ \ / / |/ _ \ \ /\ / / 
 | |__| | | (_) | |_) || |_  | | \ \  __/\ V /| |  __/\ V  V /  
  \_____|_|\___/|____/_____| |_|  \_\___| \_/ |_|\___| \_/\_/   
 | |           |  ____| | |                                     
 | |__  _   _  | |__  | | |_ ___  _ __                          
 | '_ \| | | | |  __| | | __/ _ \| '_ \                         
 | |_) | |_| | | |____| | || (_) | | | |                        
 |_.__/ \__, | |______|_|\__\___/|_| |_|                        
         __/ |                                                  
        |___/                                                   
⚠️ Disclaimer: The results in this review should be considered
friendly, yet naive, notes from an unsophisticated robot. 
Please carefully review the results listed below and share issues/ideas
by email info at globalbioticinteractions.org or by opening an issue at 
https://github.com/globalbioticinteractions/globalbioticinteractions/issues .

Review of [globalbioticinteractions/ucsb-izc] started at [2022-08-19T00:45:34+02:00].

Review of [globalbioticinteractions/ucsb-izc] included:
  - 1796 interaction(s)
  - 167 note(s)
  - 1798 info(s)

[globalbioticinteractions/ucsb-izc] has 167 reviewer note(s):
    120 found unsupported interaction type with name: [visiting]
     11 source taxon name missing: using institutionCode/collectionCode/collectionId/catalogNumber/occurrenceId as placeholder
      7 found unsupported interaction type with name: [Visiting]
      6 found unsupported interaction type with name: [from]
      4 found unsupported interaction type with name: [host of]
      3 found unsupported interaction type with name: [Sitting on]
      3 found unsupported interaction type with name: [Hovering over]
      3 found unsupported interaction type with name: [11]
      2 found unsupported interaction type with name: [resting on]
      2 found unsupported interaction type with name: [Feeding on]
      1 found unsupported interaction type with name: [Visitng]
      1 found unsupported interaction type with name: [Tended by]
      1 found unsupported interaction type with name: [Next to]
      1 found unsupported interaction type with name: [Interspersed]
      1 found unsupported interaction type with name: [feeding on]
      1 found unsupported interaction type with name: [Collected from]
```

**Comment by jhpoelen** [comment]
In tracking the changes of DwC-A associated with UCSB-IZC the following associated content can be seen:

```
 cat /var/cache/elton/datasets/globalbioticinteractions/ucsb-izc/access.tsv | grep "UCSB" | grep zip | tail -n20
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	fa776a65753f4e0abf15e21c60c1afa8fb74d5997d02c6d6a529c1fef36b3285	2022-06-25T05:12:57.603Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	fe63af46ed66abd253ee148e383fb51da6695ce3848d0bde39af18aa77d364fb	2022-07-02T05:18:28.843Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	025927c0e169c98351a940daf5b7290e8420401bbdd6068527a9c3f937e7f966	2022-07-09T17:47:35.037Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	025927c0e169c98351a940daf5b7290e8420401bbdd6068527a9c3f937e7f966	2022-07-16T05:26:02.390Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	654f4dff5b7b857e6174fb6c913b0279ec1934aae56e8ddd81c53094ea604773	2022-07-23T04:53:12.869Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	654f4dff5b7b857e6174fb6c913b0279ec1934aae56e8ddd81c53094ea604773	2022-07-30T18:09:50.193Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	b3d59aa018d3dc917288e5611180db09ffa6613647ea590152aded388f4c8eae	2022-08-06T17:12:03.539Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	95548a93125e620a02fc81d61825955082cf3330032c5f52e4ca146a6445f7c4	2022-08-13T04:59:45.248Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	b20b03528a70e013b54fed406ebc01bb2f8c19e7de50ee3fe687361ce3fc9883	2022-08-20T19:27:57.102Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	b20b03528a70e013b54fed406ebc01bb2f8c19e7de50ee3fe687361ce3fc9883	2022-08-27T06:09:47.252Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	2a70ac4adc70db8e37a3849ba763f4ca06dcb4ad0a5a3d790433b949f14af4f9	2022-09-03T06:21:27.585Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	2a70ac4adc70db8e37a3849ba763f4ca06dcb4ad0a5a3d790433b949f14af4f9	2022-09-10T10:45:02.782Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	2a70ac4adc70db8e37a3849ba763f4ca06dcb4ad0a5a3d790433b949f14af4f9	2022-09-17T04:03:00.593Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	2a70ac4adc70db8e37a3849ba763f4ca06dcb4ad0a5a3d790433b949f14af4f9	2022-09-24T19:55:05.929Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	2a70ac4adc70db8e37a3849ba763f4ca06dcb4ad0a5a3d790433b949f14af4f9	2022-10-01T21:09:51.960Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	17ba205927c1cc16b616d2bc2d0bd6b1bf31320b9aa7e0d76ab458adfeb2275f	2022-10-08T17:10:20.834Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	ff5d44e00bfa41e6457af9de5adb0e9bc475bf62f185382ebdf526c7ae84e9b6	2022-10-15T08:38:50.512Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	ff5d44e00bfa41e6457af9de5adb0e9bc475bf62f185382ebdf526c7ae84e9b6	2022-10-22T22:48:52.146Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	30482abfb4fcc82d91a069a8e3d93bf22a42021fe9dd97d73b3bae3c84ee2de1	2022-10-29T08:36:36.626Z	
globalbioticinteractions/ucsb-izc	https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip	9322be6c8b4860b7ecd5486c3210f130bbde771c7dd810a4cd2fa13f34480e46	2022-11-01T23:46:56.923Z	
```

**Comment by jhpoelen** [comment]
Note that the UCSB IZC index configuration was changed after Aug 2022 via https://github.com/globalbioticinteractions/ucsb-izc/commit/4d997dbe8e86398f9f7f4d7851013e788073ae9c .

**Comment by jhpoelen** [comment]
when using the old 2022-08-13 UCSB-IZC DwC-A with content hash hash://sha256/95548a93125e620a02fc81d61825955082cf3330032c5f52e4ca146a6445f7c4 , I was able to reproduce low number of indexed interactions:

```
$ git diff
diff --git a/globi.json b/globi.json
index ba2bd35..7c10e83 100644
--- a/globi.json
+++ b/globi.json
@@ -1,5 +1,6 @@
 {
   "format": "dwca",
   "citation": "University of California Santa Barbara Invertebrate Zoology Collection",
-  "url": "https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip"
+  "url": "95548a93125e620a02fc81d61825955082cf3330032c5f52e4ca146a6445f7c4",
+  "_url": "https://serv.biokic.asu.edu/ecdysis/content/dwca/UCSB-IZC_DwC-A.zip"
 }
```

```
$ elton interactions  | wc -l
listing interactions [local]... done.
14
```

**Comment by jhpoelen** [comment]
on removing the interaction_types_mapping.csv, the expected results are found, using the *old* dwca - 

```
$ mv interaction_types_mapping.csv interaction_types_mapping.csv.old
jorrit@larus:~/proj/globi/data-new/ucsb-izc$ rm -rf datasets/
jorrit@larus:~/proj/globi/data-new/ucsb-izc$ elton interactions | wc -l.
listing interactions [local]... done.
1937
```

this suggests that the interaction_types_mapping.csv is the reason for the large number of unmapped interaction types.

**Comment by jhpoelen** [comment]
Downgrading elton to v0.2.14 (March 2022) with the interaction_type_mappings.csv still produces the low amount of interactions, so it does not appear to be a change in elton.

**Comment by jhpoelen** [comment]
after removing entries that only differed by case (e.g., visiting and Visiting), the expected result was found:

```
$ git diff
diff --git a/interaction_types_mapping.csv b/interaction_types_mapping.csv
index f247786..71a4b2c 100644
--- a/interaction_types_mapping.csv
+++ b/interaction_types_mapping.csv
@@ -1,11 +1,9 @@
 provided_interaction_type_label,provided_interaction_type_id,mapped_to_interaction_type_label,mapped_to_interaction_type_id
 visiting,,visits,http://purl.obolibrary.org/obo/RO_0002618
-Visiting,,visits,http://purl.obolibrary.org/obo/RO_0002618
 from,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
 host of,,hostOf,http://purl.obolibrary.org/obo/RO_0002453
 Sitting on,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
 resting on,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
-Feeding on,,eats,http://purl.obolibrary.org/obo/RO_0002470
 Visitng,,visits,http://purl.obolibrary.org/obo/RO_0002618
 Tended by,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
 Next to,,ecologically co-occurs with,http://purl.obolibrary.org/obo/RO_0008506
```

```
$ elton interactions | wc -l
listing interactions [local]... done.
1946
```

So, it appears that the root cause is the silent failure of elton to map interactions after tripping up after finding some similar mapping definitions.

**Comment by jhpoelen** [comment]
after removing entries that only differed by case (e.g., visiting and Visiting), the expected result was found:

```
$ git diff
diff --git a/interaction_types_mapping.csv b/interaction_types_mapping.csv
index f247786..71a4b2c 100644
--- a/interaction_types_mapping.csv
+++ b/interaction_types_mapping.csv
@@ -1,11 +1,9 @@
 provided_interaction_type_label,provided_interaction_type_id,mapped_to_interaction_type_label,mapped_to_interaction_type_id
 visiting,,visits,http://purl.obolibrary.org/obo/RO_0002618
-Visiting,,visits,http://purl.obolibrary.org/obo/RO_0002618
 from,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
 host of,,hostOf,http://purl.obolibrary.org/obo/RO_0002453
 Sitting on,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
 resting on,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
-Feeding on,,eats,http://purl.obolibrary.org/obo/RO_0002470
 Visitng,,visits,http://purl.obolibrary.org/obo/RO_0002618
 Tended by,,interactsWith,http://purl.obolibrary.org/obo/RO_0002437
 Next to,,ecologically co-occurs with,http://purl.obolibrary.org/obo/RO_0008506
```

```
$ elton interactions | wc -l
listing interactions [local]... done.
1946
```

So, it appears that the root cause is the silent failure of elton to map interactions after tripping up after finding some similar mapping definitions.

**Comment by jhpoelen** [comment]
@seltmann I was able to reproduce the cause of the unexpected UCSB-IZC interaction counts. Also, I've implemented a workaround. 

As far as future fixes - how would you like Elton to tell you that they found a confusing ambiguous mapping? 

And, related,

Do you want Elton to be ok with multiple mappings that only differ by case (e.g., [on] and [On] that map to the same interaction type) ?

**Comment by jhpoelen** [comment]
@seltmann you should be able to re-run the big bee report and produce expected results. Apologies for the delay and confusion related to this silly issue. And, thanks for taking the time to report it.

**Comment by jhpoelen** [comment]
btw - via Github Actions after applying the workaround https://github.com/globalbioticinteractions/ucsb-izc/commit/66a4e39589d1dfa299d07985546c4be522ff60d8 

https://github.com/globalbioticinteractions/ucsb-izc/actions/runs/3387290582/jobs/5627837545


```
Review of [globalbioticinteractions/ucsb-izc] included:
  - 1946 interaction(s)
  - 17 note(s)
  - 1948 info(s)

[globalbioticinteractions/ucsb-izc] has 17 reviewer note(s):
     11 source taxon name missing: using institutionCode/collectionCode/collectionId/catalogNumber/occurrenceId as placeholder
      3 found unsupported interaction type with name: [Hovering over]
      3 found unsupported interaction type with name: [11]
```

**Comment by seltmann** [comment]
@jhpoelen thank you for tracking down the issue. I would expect elton to send me a message such as "elton found duplication of interaction type in "interaction_types_mapping.csv." This could be a review note?

**Comment by jhpoelen** [comment]
Yes, the interaction type mapping errors now appear as a review note. 

Thanks for the suggestion and apologies for my late reply.
